"""
Auto-generates documentation for solutions.
"""

from pathlib import Path
from datetime import datetime
from typing import Dict, Any


def generate_documentation(problem_dir: Path, problem: Dict, solution: Dict):
    """Generate all documentation files."""
    # Generate README.md
    generate_readme(problem_dir, problem, solution)

    # Generate ARCHITECTURE.md
    generate_architecture(problem_dir, problem, solution)

    # Generate AI_AGENTS.md
    generate_ai_docs(problem_dir, problem)

    # Generate API.md
    generate_api_docs(problem_dir, solution)


def generate_readme(problem_dir: Path, problem: Dict, solution: Dict):
    """Generate main README.md."""
    date_str = datetime.now().strftime("%Y-%m-%d")
    solution_type = solution.get("type", "fullstack")

    readme_content = f"""# {problem['title']}

> AI-generated solution for a real-world problem
> Date: {date_str}

## Problem Statement

{problem.get('description', 'N/A')}

**Source:** {problem.get('source', 'N/A')}  
**Category:** {problem.get('category', 'N/A')}  
**URL:** {problem.get('url', 'N/A')}

## Why This Problem?

{problem.get('reason', 'This problem was identified as a trending need in the tech community.')}

## Solution Overview

This is a **{solution_type}** solution that uses AI agents to solve the problem.

### Tech Stack

| Layer | Technology |
|-------|------------|
| Frontend | Next.js (React) |
| Backend | Python (FastAPI) |
| AI | Ollama (Local LLM) |

## Quick Start

### Prerequisites

- Python 3.10+
- Node.js 18+
- Ollama installed

### Installation

1. **Install Ollama:**
   ```bash
   curl -fsSL https://ollama.com/install.sh | sh
   ```

2. **Pull the AI model:**
   ```bash
   ollama pull llama3.2
   ```

3. **Backend setup:**
   ```bash
   cd backend
   python -m venv venv
   source venv/bin/activate
   pip install -r requirements.txt
   uvicorn main:app --reload
   ```

4. **Frontend setup:**
   ```bash
   cd frontend
   npm install
   npm run dev
   ```

5. **Open:** http://localhost:3000

## How It Works

```
User Request → Next.js Frontend → FastAPI Backend → AI Agent → Response
```

## Project Structure

```
{problem_dir.name}/
├── README.md           # This file
├── PROBLEM.md          # Problem description
├── metadata.json       # Problem metadata
├── frontend/           # Next.js app
│   ├── app/
│   │   ├── page.tsx
│   │   ├── layout.tsx
│   │   └── globals.css
│   └── package.json
├── backend/            # Python API
│   ├── main.py
│   ├── requirements.txt
│   └── agents/
│       └── agent.py
└── docs/
    ├── ARCHITECTURE.md
    ├── AI_AGENTS.md
    └── API.md
```

## AI Agent Features

- **Problem Analysis:** AI analyzes the problem and suggests approach
- **Code Generation:** Generates working code solution
- **Local Processing:** All AI runs locally via Ollama (no API costs)

## License

MIT License - Generated by Daily Problem Solver
"""

    with open(problem_dir / "README.md", "w") as f:
        f.write(readme_content)


def generate_architecture(problem_dir: Path, problem: Dict, solution: Dict):
    """Generate ARCHITECTURE.md."""
    content = f"""# Architecture Documentation

## System Overview

This solution implements a full-stack application to solve:
**{problem['title']}**

## High-Level Architecture

```
┌─────────────────────────────────────────────────────────────┐
│                      CLIENT (Browser)                        │
│                     Next.js Frontend                         │
└──────────────────────────┬──────────────────────────────────┘
                           │ HTTP/REST
                           ▼
┌─────────────────────────────────────────────────────────────┐
│                      API SERVER                              │
│                   FastAPI Backend                            │
└──────────────────────────┬──────────────────────────────────┘
                           │
                           ▼
┌─────────────────────────────────────────────────────────────┐
│                     AI AGENT                                │
│                   Ollama + LLM                              │
└─────────────────────────────────────────────────────────────┘
```

## Components

### Frontend (Next.js)

- **Framework:** Next.js 14 with App Router
- **Language:** TypeScript/JavaScript
- **Styling:** Tailwind CSS
- **State:** React hooks

### Backend (Python)

- **Framework:** FastAPI
- **AI:** Ollama (local LLM)
- **Language:** Python 3.10+

### AI Agent

- **Model:** Llama 3.2 (via Ollama)
- **Execution:** Local machine
- **Cost:** Free (no API calls)

## Data Flow

1. User interacts with Next.js frontend
2. Frontend sends request to FastAPI backend
3. Backend invokes AI agent
4. AI agent processes with local LLM
5. Response returned to frontend
6. Frontend displays solution

## Security Notes

- All AI processing is local
- No data sent to external APIs
- No API keys required
"""

    with open(problem_dir / "docs" / "ARCHITECTURE.md", "w") as f:
        f.write(content)


def generate_ai_docs(problem_dir: Path, problem: Dict):
    """Generate AI_AGENTS.md."""
    content = f"""# AI Agents Documentation

## Overview

This solution uses AI agents to solve: **{problem['title']}**

## Agent Architecture

### ProblemSolverAgent

The main agent that orchestrates problem solving:

```python
class ProblemSolverAgent:
    def __init__(self, model="llama3.2"):
        self.model = model

    def analyze(self, problem):
        # Analyzes problem and suggests approach
        pass

    def generate_code(self, problem, approach):
        # Generates working code
        pass
```

## How It Works

### Step 1: Problem Analysis

The agent analyzes the problem using natural language understanding:

- Identifies key requirements
- Determines best approach
- Suggests implementation strategy

### Step 2: Code Generation

Based on analysis, the agent generates:

- Complete working code
- Required dependencies
- Configuration files

### Step 3: Documentation

Auto-generates:

- README with setup instructions
- Architecture documentation
- API documentation

## Model Information

| Property | Value |
|----------|-------|
| Model | Llama 3.2 |
| Size | 3B parameters |
| Location | Local machine |
| API Calls | None (100% local) |
| Cost | $0 |

## Customization

### Changing the Model

Edit `backend/agents/agent.py`:

```python
# Use different model
agent = ProblemSolverAgent(model="mistral")
```

### Adjusting Prompts

Modify prompts in the agent to change behavior:

```python
prompt = f"""
Your custom prompt here...
Problem: {{problem}}
"""
```

## Performance

- **Analysis Time:** ~2-5 seconds
- **Code Generation:** ~5-10 seconds
- **Total:** < 15 seconds per problem

## Future Enhancements

- [ ] Add multi-agent collaboration
- [ ] Implement agent memory
- [ ] Add code testing agent
- [ ] Support multiple languages
"""

    with open(problem_dir / "docs" / "AI_AGENTS.md", "w") as f:
        f.write(content)


def generate_api_docs(problem_dir: Path, solution: Dict):
    """Generate API.md."""
    content = """# API Documentation

## Base URL

```
http://localhost:8000
```

## Endpoints

### POST /api/solve

Solve a problem using AI agent.

**Request Body:**

```json
{
    "problem": "string",
    "description": "string"
}
```

**Response:**

```json
{
    "problem": "string",
    "solution": "string",
    "code": "string"
}
```

**Example:**

```bash
curl -X POST http://localhost:8000/api/solve \\
  -H "Content-Type: application/json" \\
  -d '{"problem": "How to organize files", "description": "Need automated file organizer"}'
```

### GET /api/health

Health check endpoint.

**Response:**

```json
{
    "status": "healthy"
}
```

## Error Handling

All errors return standard HTTP status codes:

| Code | Description |
|------|-------------|
| 200 | Success |
| 400 | Bad Request |
| 500 | Server Error |

## Rate Limiting

No rate limiting - runs locally.

## Authentication

No authentication required - local development only.
"""

    with open(problem_dir / "docs" / "API.md", "w") as f:
        f.write(content)
