"""
Auto-generates documentation for solutions.
"""

from pathlib import Path
from datetime import datetime
from typing import Dict, Any


def generate_documentation(problem_dir: Path, problem: Dict, solution: Dict):
    """Generate all documentation files."""
    generate_readme(problem_dir, problem, solution)
    generate_architecture(problem_dir, problem, solution)
    generate_ai_docs(problem_dir, problem)
    generate_api_docs(problem_dir, solution)


def generate_readme(problem_dir: Path, problem: Dict, solution: Dict):
    """Generate main README.md."""
    date_str = datetime.now().strftime("%Y-%m-%d")
    solution_type = solution.get("type", "fullstack")
    title = problem['title']
    desc = problem.get('description', 'N/A')
    source = problem.get('source', 'N/A')
    category = problem.get('category', 'N/A')
    url = problem.get('url', 'N/A')
    reason = problem.get('reason', 'This problem was identified as a trending need in the tech community.')
    dirname = problem_dir.name

    readme_content = f"""# {title}

> AI-generated solution for a real-world problem
> Date: {date_str}

## Problem Statement

{desc}

**Source:** {source}
**Category:** {category}
**URL:** {url}

## Why This Problem?

{reason}

## Solution Overview

This is a **{solution_type}** solution that uses AI agents to solve the problem.

### Tech Stack

| Layer | Technology |
|-------|------------|
| Frontend | Next.js (React) |
| Backend | Python (FastAPI) |
| AI | HuggingFace API (Free) |

## Quick Start

### Prerequisites

- Python 3.10+
- Node.js 18+

### Installation

1. **Backend setup:**
   ```bash
   cd backend
   python -m venv venv
   source venv/bin/activate
   pip install -r requirements.txt
   uvicorn main:app --reload
   ```

2. **Frontend setup:**
   ```bash
   cd frontend
   npm install
   npm run dev
   ```

3. **Open:** http://localhost:3000

## How It Works

```
User Request -> Next.js Frontend -> FastAPI Backend -> AI API -> Response
```

## Project Structure

```
{dirname}/
├── README.md           # This file
├── PROBLEM.md          # Problem description
├── metadata.json       # Problem metadata
├── frontend/           # Next.js app
│   ├── app/
│   │   ├── page.tsx
│   │   ├── layout.tsx
│   │   └── globals.css
│   └── package.json
├── backend/            # Python API
│   ├── main.py
│   ├── requirements.txt
│   └── agents/
│       └── agent.py
└── docs/
    ├── ARCHITECTURE.md
    ├── AI_AGENTS.md
    └── API.md
```

## AI Agent Features

- **Problem Analysis:** AI analyzes the problem and suggests approach
- **Code Generation:** Generates working code solution
- **Free API:** Uses HuggingFace free inference API

## License

MIT License - Generated by Daily Problem Solver
"""

    with open(problem_dir / "README.md", "w") as f:
        f.write(readme_content)


def generate_architecture(problem_dir: Path, problem: Dict, solution: Dict):
    """Generate ARCHITECTURE.md."""
    title = problem['title']

    content = f"""# Architecture Documentation

## System Overview

This solution implements a full-stack application to solve:
**{title}**

## High-Level Architecture

```
+-----------------------------------------------------+
|                      CLIENT (Browser)                |
|                     Next.js Frontend                 |
+-----------------------------------------------------+
                           |
                           v
+-----------------------------------------------------+
|                      API SERVER                      |
|                   FastAPI Backend                    |
+-----------------------------------------------------+
                           |
                           v
+-----------------------------------------------------+
|                     AI SERVICE                       |
|               HuggingFace Free API                   |
+-----------------------------------------------------+
```

## Components

### Frontend (Next.js)

- **Framework:** Next.js 14 with App Router
- **Language:** TypeScript/JavaScript
- **Styling:** Tailwind CSS
- **State:** React hooks

### Backend (Python)

- **Framework:** FastAPI
- **AI:** HuggingFace Free Inference API
- **Language:** Python 3.10+

## Data Flow

1. User interacts with Next.js frontend
2. Frontend sends request to FastAPI backend
3. Backend calls HuggingFace API
4. AI processes the request
5. Response returned to frontend
6. Frontend displays solution

## Security Notes

- No API keys required (free tier)
- All processing via HTTPS
- No sensitive data stored
"""

    with open(problem_dir / "docs" / "ARCHITECTURE.md", "w") as f:
        f.write(content)


def generate_ai_docs(problem_dir: Path, problem: Dict):
    """Generate AI_AGENTS.md."""
    title = problem['title']

    content = f"""# AI Agents Documentation

## Overview

This solution uses AI to solve: **{title}**

## Agent Architecture

### ProblemSolverAgent

The main agent that orchestrates problem solving:

```python
class ProblemSolverAgent:
    def __init__(self):
        self.api_url = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2"

    def analyze(self, problem):
        # Analyzes problem and suggests approach
        pass

    def generate_code(self, problem, approach):
        # Generates working code
        pass
```

## How It Works

### Step 1: Problem Analysis

The agent analyzes the problem using natural language understanding:

- Identifies key requirements
- Determines best approach
- Suggests implementation strategy

### Step 2: Code Generation

Based on analysis, the agent generates:

- Complete working code
- Required dependencies
- Configuration files

### Step 3: Documentation

Auto-generates:

- README with setup instructions
- Architecture documentation
- API documentation

## API Information

| Property | Value |
|----------|-------|
| Provider | HuggingFace |
| Model | Mistral-7B-Instruct |
| Cost | Free tier |
| API Calls | Rate limited |

## Customization

### Adjusting Prompts

Modify prompts in the agent to change behavior:

```python
prompt = f"Your custom prompt here... Problem: {{problem}}"
```

## Performance

- **Analysis Time:** ~2-5 seconds
- **Code Generation:** ~5-10 seconds
- **Total:** < 15 seconds per problem

## Future Enhancements

- [ ] Add multi-agent collaboration
- [ ] Implement agent memory
- [ ] Add code testing agent
- [ ] Support multiple languages
"""

    with open(problem_dir / "docs" / "AI_AGENTS.md", "w") as f:
        f.write(content)


def generate_api_docs(problem_dir: Path, solution: Dict):
    """Generate API.md."""
    content = """# API Documentation

## Base URL

```
http://localhost:8000
```

## Endpoints

### POST /api/solve

Solve a problem using AI agent.

**Request Body:**

```json
{
    "problem": "string",
    "description": "string"
}
```

**Response:**

```json
{
    "problem": "string",
    "solution": "string",
    "code": "string"
}
```

**Example:**

```bash
curl -X POST http://localhost:8000/api/solve \\
  -H "Content-Type: application/json" \\
  -d '{"problem": "How to organize files", "description": "Need automated file organizer"}'
```

### GET /api/health

Health check endpoint.

**Response:**

```json
{
    "status": "healthy"
}
```

## Error Handling

All errors return standard HTTP status codes:

| Code | Description |
|------|-------------|
| 200 | Success |
| 400 | Bad Request |
| 500 | Server Error |

## Rate Limiting

No rate limiting - runs locally.

## Authentication

No authentication required - local development only.
"""

    with open(problem_dir / "docs" / "API.md", "w") as f:
        f.write(content)
